### ISSUE TITLE
fix problem X

### ISSUE THREAD

**Issue by physikerwelt** [alexeygrigorev/namespacediscovery-pipeline#11]
After testing the latests version I had the following problem that did not occour before the git update:
```
physikerwelt@mlp:~/namespacediscovery-pipeline/src$ time python main.py
DEBUG:nd.read:reading MLP output from /home/physikerwelt/mlp-output/...
DEBUG:nd.read:skipped 0 empty, 0 small and 7501 uncategorized documents
DEBUG:nd.read:read 22512 documents
DEBUG:nd.read:removing infrequent definitions with frequency <= 1...
DEBUG:nd.read:there are 35144 definitions with frequency <= 1, removing them...
DEBUG:nd.read:removed
DEBUG:nd.read:removing infrequent identifiers with frequency <= 2...
DEBUG:nd.read:removed
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    mlp_data = ivs.process(ivs.IDV_NO_DEF, mlp_data)
TypeError: process() takes exactly 3 arguments (2 given)

real    0m11.297s
user    0m9.878s
sys     0m1.395s
```
I also noticed that I had to update the paths in [main.py](https://github.com/alexeygrigorev/namespacediscovery-pipeline/blob/master/src/main.py#L27-L28) even though they are already defined in the luigi.cfg

Please lset me know, if you need futuer information to track back the problem. You can also login to the mlp instance.

**Comment by alexeygrigorev** [comment]
You need to run `python pipeline.py`. Please let me know if it solves the
problem.

Probably I'll need to delete `main.py` so it doesn't confuse anybody (or
modify it)
