### ISSUE TITLE
expose classification name in the output

### ISSUE THREAD

**Issue by physikerwelt** [alexeygrigorev/namespacediscovery-pipeline#13]
The classification id should appear in the final output
for instance
MSC classes: 	33C10, 33C05, 44A20

**Comment by alexeygrigorev** [comment]
Done, now the category information is added to the output:


	=== Fiber spaces and bundles ===
	Category information
	* reference category:  Fiber spaces and bundles
	* code: 55Rxx (MSC)
	* wiki categories: [(u'Abstract algebra', 3), (u'Fiber bundles', 2), (u'Continuous mappings', 2)]

	Cluster information:
	* cluster id: 8626
	* matching score: 0.40981661373
	* purity: 1.0
	* matching keywords: [u'classifying', u'fiber', u'space', u'bundles', u'algebraic', u'homotopy', u'topology']

	'''Definitions:'''
	* <math>X</math>: topological space (4.553)
	* <math>Z</math>: space (1.974)
	* <math>Y</math>: topology (1.821)
	* ...
