### ISSUE TITLE
Parameter for [MlpResultsReadTask]/categories_processed - path to the category information

### ISSUE THREAD

**Issue by yash-nagar** [alexeygrigorev/namespacediscovery-pipeline#17]
Can you please provide description for the parameter [MlpResultsReadTask]/categories_processed in the configuration file luigi.cfg

**Comment by alexeygrigorev** [comment]
As far as I remember that's the categories from dbpedia. Please look at this notebook: https://github.com/alexeygrigorev/namespacediscovery/blob/master/thesis_code/DBPedia_ttl_procss.ipynb (it's a bit sloppy, sorry) 

Later today I'll have a look if I still keep the processed file somewhere at my home computer. Please ping me if I forget to do it.

**Comment by yash-nagar** [comment]
I would like to remind you about sending the processed file.

**Comment by alexeygrigorev** [comment]
Here you go

[category_info_refined.txt](https://github.com/alexeygrigorev/namespacediscovery-pipeline/files/656606/category_info_refined.txt)
