### ISSUE TITLE
Enable Wikipedia Output.

### ISSUE THREAD

**Issue by physikerwelt** [alexeygrigorev/namespacediscovery-pipeline#5]
Make it so that the program outputs wiki markup, like on http://0agr.ru/wiki/index.php/Discovered_namespaces?action=edit

**Comment by alexeygrigorev** [comment]
to render the results in wiki markup, use `output_format: wiki` in luigi.cfg. For json it's `json`. 

Example: 

	= ROOT =
	== Algebraic geometry ==
	=== Affine geometry ===
	wiki categories: [(u'Affine geometry', 3), (u'Fields of mathematics', 2), (u'Geometry', 2)]

	Cluster information:
	* cluster id: 1607
	* matching score: 0.488566012336
	* purity: 1.0
	* matching keywords: [u'geometry', u'affine']

	'''Definitions:'''
	* <math>T</math>: affine transformation (1.974)
	* <math>x_1</math>: linear combination (0.926)
	* <math>α_i</math>: scalars (0.926)
	* <math>S</math>: cone (0.914)
	* <math>P</math>: convex combination (0.871)
