### ISSUE TITLE
make tokenization configurabe

### ISSUE THREAD

**Issue by physikerwelt** [alexeygrigorev/namespacediscovery-pipeline#6]
Provide a mechanism that tokenization can be switch off, and the full description like "Cauchy stress tensor" would be used.

**Comment by alexeygrigorev** [comment]
added another way of incorporating definitions into the vector space - "FULL". 

With stemming switched on, the values for $X$ is "linear combination" and $k$ is "random vector" in this vector space look like `X_linear combin` and `k_random vector`.

To use it, set `isv_type` to `full` in luigi.cfg
