### ISSUE TITLE
Make a switch to switch off stemming

### ISSUE THREAD

**Issue by physikerwelt** [alexeygrigorev/namespacediscovery-pipeline#7]
We want to measure the influence of stemming and therefore need to be able to compare ther results with and without stemming.

**Comment by physikerwelt** [comment]
In adddition there is a math specific stemming algorithm, that we might want to test. However, since this algorithm is written in Java this has to happen in a pre-preocessing step

**Comment by alexeygrigorev** [comment]
set `ivs_stemmer` to `none` in `luigi.cfg` to switch off stemming, or set it to `snowball` to use a snowball stemmer
