### ISSUE TITLE
Use only the last word from tokenization

### ISSUE THREAD

**Issue by physikerwelt** [alexeygrigorev/namespacediscovery-pipeline#8]
e.g. from Cauchy stress tensonr only "tensor" should be used since "cauchy" and "stress" can not be considered as meaningful definitions. Especially for the strong association this would be important. For weak association the approach to use (\sigma,cauchy,stress,tensor) as the identifier vector seems reasonable.

**Comment by alexeygrigorev** [comment]
added another way of incorporating definitions into the vector space - "STRONG LAST".

With stemming switched on, the values for $X$ is "linear combination" and $k$ is "random vector" in this vector space look like `X_combin` and `k_vector`.

To use it, set `isv_type` to `strong_last` in luigi.cfg
